language: go

go:
  - 1.8.x
  - tip

before_install:
  - go get github.com/xwb1989/sqlparser
  - go get github.com/olivere/elastic

script:
  - go test -run TestCoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
